name: Security Check
description: Scan for security vulnerabilities with bandit

runs:
  using: composite
  steps:
    - name: Run security scan
      run: |
        cd study_shoes_store
        bandit -r shoes_api --exclude shoes_api/migrations,shoes_api/tests.py -f json -o bandit-report.json || true
      shell: bash

    - name: Display security report
      run: |
        cd study_shoes_store
        bandit -r shoes_api --exclude shoes_api/migrations,shoes_api/tests.py
      shell: bash
