# Generated by Django 3.2.5 on 2021-07-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_api', '0003_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
