# Generated by Django 3.2.5 on 2021-07-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_api', '0004_alter_client_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
