# Generated by Django 3.2.5 on 2021-07-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_api', '0006_auto_20210710_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
