# Generated by Django 3.2.5 on 2021-07-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_api', '0008_auto_20210711_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='seller_user',
            new_name='seller',
        ),
    ]
