name: Lint Code
description: Check code style and quality with ruff

runs:
  using: composite
  steps:
    - name: Run ruff check
      run: |
        cd study_shoes_store
        ruff check shoes_api --select=E,W,F --exclude=shoes_api/migrations
      shell: bash

    - name: Run ruff format check
      run: |
        cd study_shoes_store
        ruff format shoes_api --check --exclude=shoes_api/migrations
      shell: bash
