name: Generate Coverage Report
description: Generate and upload coverage report

runs:
  using: composite
  steps:
    - name: Generate coverage
      run: |
        cd study_shoes_store
        coverage run --source='shoes_api' manage.py test shoes_api
        coverage report
        coverage xml -o coverage.xml
      shell: bash

    - name: Upload to Codecov
      uses: codecov/codecov-action@v6
      with:
        files: ./study_shoes_store/.coverage
        flags: unittests
        fail_ci_if_error: false
