name: Run Tests
description: Execute test suite

runs:
  using: composite
  steps:
    - name: Run tests
      run: |
        cd study_shoes_store
        coverage run --source='shoes_api' manage.py test shoes_api -v 2
      shell: bash
