name: Tests

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

on:
  workflow_dispatch:

  # push:
  #   branches: [ main, master, develop ]
  # pull_request:
  #   branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.13-slim

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-python-env
      - uses: ./.github/actions/lint

  security:
    runs-on: ubuntu-latest
    container:
      image: python:3.13-slim

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-python-env
      - uses: ./.github/actions/security

      - name: Upload Bandit artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-report
          path: study_shoes_store/bandit-report.json
          if-no-files-found: ignore

  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.13-slim

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-python-env
      - uses: ./.github/actions/run-tests
      - uses: ./.github/actions/coverage-report

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: |
            study_shoes_store/.coverage
            study_shoes_store/coverage.xml
          if-no-files-found: ignore
